baseURL = "https://hackeradam.com"
languageCode = "en-us"
title = "Adam Hacks"
author = "Adam Thompson"
theme = "h4x0r"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
    description = "Thoughts on computer science, math, and general geekery from Adam Thompson."
    rssFeedDescription = "summary"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/serialphotog"
    [[params.socialIcons]]
        name = "mastodon"
        url = "https://mastodon.social/@serialphotog"
    [[params.socialIcons]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/adam-thompson-swe/"
    [[params.socialIcons]]
        name = "Instagram"
        url = "https://www.instagram.com/adamhacksthings"
    [[params.socialIcons]]
        name = "Link"
        url = "https://adamthompsonphoto.com"
    [[params.socialIcons]]
        name = "RSS"
        url = "/index.xml"

[menu]
    [[menu.main]]
        pageRef="/"
        name = "Blog"
        weight = 10
    [[menu.main]]
        pageRef="/microblog"
        name = "Microblog"
        weight = 15
    [[menu.main]]
        pageRef = "/references"
        name = "References"
        weight = 18
    [[menu.main]]
        pageRef = "/search"
        name = "Search"
        weight = 19
    [[menu.main]]
        pageRef="/about"
        name = "About"
        weight = 20
    [[menu.main]]
        pageRef="/blogroll"
        name = "Blogroll"
        weight = 30
    [[menu.main]]
        url = "https://www.adamthompsonphoto.com"
        name = "Photography"
        weight = 50
    [[menu.main]]
        name = "GitHub"
        url = "https://github.com/serialphotog"
        weight = 60
    [[menu.main]]
        pageRef = "/faq"
        name = "FAQ"
        weight = 70
    [[menu.main]]
        pageRef = "/changelog"
        name = "Changelog"
        weight = 75
    [[menu.main]]
        url = "/index.xml"
        name = "RSS"
        weight = 80

[markup]
  [markup.highlight]
    noclasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 1 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[taxonomies]
    series = 'series'
    tags = 'tags'
