baseURL = "https://hackeradam.com"
languageCode = "en-us"
title = "Adam Hacks"
theme = "m10c"
avatar = "/static/avatar.jpg"
paginate = 10

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 3
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 4
    [[menu.main]]
        identifier = "references"
        name = "References"
        url = "/references"
        weight = 5

[params]
    author = "Adam Thompson"
    description = "Thoughts on computer science, math, and general geekery from Adam Thompson."
    email = "adam@hackeradam.com"

    [[params.social]]
        icon = "github"
        name = "Github"
        url = "https://github.com/serialphotog"
    [[params.social]]
        icon = "twitter"
        name = "Twitter"
        url = "https://twitter.com/serialphotog"
    [[params.social]]
        icon = "link"
        name = "Photography Portfolio"
        url = "https://serialphotog.com"
    [params.style]
        darkestColor = "#242930"
        darkColor = "#353b43"
        lightColor = "#afbac4"
        lightestColor = "#fff"
         primaryColor = "#57cc8a"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true