baseURL = "https://hackeradam.com"
languageCode = "en-us"
title = "Adam Hacks"
author = "Adam Thompson"
copyright = "Copyright © 2024, Adam Thompson."
theme = "hugo-bearblog"
paginate = 10

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[menus]
  [[menus.main]]
    name = 'Blog'
    pageRef = '/'
    weight = 1
  [[menus.main]]
    name = 'References'
    pageRef = '/references'
    weight = 2
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 3

[params]
    description = "Thoughts on computer science, math, and general geekery from Adam Thompson."

[markup.goldmark.renderer]
    unsafe = true

[taxonomies]
    series = 'series'
    tags = 'tags'
