baseURL = "https://hackeradam.com"
languageCode = "en-us"
title = "Adam Hacks"
author = "Adam Thompson"
theme = "hugo-bearblog"
paginate = 10

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
    description = "Thoughts on computer science, math, and general geekery from Adam Thompson."

[markup.goldmark.renderer]
    unsafe = true

[taxonomies]
    series = 'series'
    tags = 'tags'
